import { categoryAccents, motion, radii, themes, type ThemeColors } from './tokens';

const kebab = (value: string) => value.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

function themeVariables(theme: ThemeColors, indent: string): string {
  return Object.entries(theme)
    .map(([key, value]) => `${indent}--${kebab(key)}: ${value};`)
    .join('\n');
}

/**
 * Generates tokens.css for Tailwind CSS 4: CSS variables for both themes and an
 * `@theme inline` block exposing them as utilities (bg-primary, text-highlight,
 * bg-cat-outdoor-bg…). Run `pnpm --filter @doulisha/ui-tokens build:css`.
 */
export function generateTokensCss(): string {
  const colorNames = Object.keys(themes.light).map(kebab);
  const categoryVars = Object.entries(categoryAccents).flatMap(([name, c]) => [
    `  --cat-${name}: ${c.solid};`,
    `  --cat-${name}-bg: ${c.bg};`,
    `  --cat-${name}-fg: ${c.fg};`,
  ]);

  return `/* Generated by @doulisha/ui-tokens (src/css.ts). Do not edit by hand. */

:root {
${themeVariables(themes.light, '  ')}
${categoryVars.join('\n')}
  --radius: ${radii.lg};
  --duration-fast: ${motion.fast};
  --duration-base: ${motion.base};
  --duration-slow: ${motion.slow};
  --ease-standard: ${motion.easing};
  color-scheme: light;
}

.dark {
${themeVariables(themes.dark, '  ')}
  color-scheme: dark;
}

@theme inline {
${colorNames.map((name) => `  --color-${name}: var(--${name});`).join('\n')}
${Object.keys(categoryAccents)
  .flatMap((name) => [
    `  --color-cat-${name}: var(--cat-${name});`,
    `  --color-cat-${name}-bg: var(--cat-${name}-bg);`,
    `  --color-cat-${name}-fg: var(--cat-${name}-fg);`,
  ])
  .join('\n')}
  --radius-sm: ${radii.sm};
  --radius-md: ${radii.md};
  --radius-lg: ${radii.lg};
  --radius-xl: ${radii.xl};
}
`;
}
