import { sql } from 'drizzle-orm';
import { customType, timestamp, uuid } from 'drizzle-orm/pg-core';

/** Primary key: UUID v7 (time-sortable), generated by Postgres 18 (ADR 0007). */
export const id = () =>
  uuid()
    .primaryKey()
    .default(sql`uuidv7()`);

export const createdAt = () => timestamp({ withTimezone: true }).notNull().defaultNow();

export const updatedAt = () =>
  timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

/** Soft delete for user content (BUILD_PROMPT section 5). */
export const deletedAt = () => timestamp({ withTimezone: true });

export const timestamps = () => ({ createdAt: createdAt(), updatedAt: updatedAt() });

/** Text in the three interface languages, e.g. category names. */
export interface LocalizedText {
  ar: string;
  fr: string;
  en: string;
}

/**
 * PostGIS `geography(Point, 4326)`: distances in metres, GiST-indexable.
 * Stored and read as WGS84 longitude/latitude.
 */
export interface GeoPoint {
  lng: number;
  lat: number;
}

export const geographyPoint = customType<{ data: GeoPoint; driverData: string }>({
  dataType() {
    return 'geography(Point, 4326)';
  },
  toDriver(value) {
    return `SRID=4326;POINT(${value.lng} ${value.lat})`;
  },
  fromDriver(value) {
    return parseEwkbPoint(value);
  },
});

/**
 * Parses the hex EWKB that Postgres returns for a geography point
 * (little- or big-endian, with or without SRID).
 */
export function parseEwkbPoint(hex: string): GeoPoint {
  const bytes = Uint8Array.from(hex.match(/../g) ?? [], (b) => parseInt(b, 16));
  const view = new DataView(bytes.buffer);
  const littleEndian = view.getUint8(0) === 1;
  const type = view.getUint32(1, littleEndian);
  const hasSrid = (type & 0x20000000) !== 0;
  const offset = hasSrid ? 9 : 5;
  return {
    lng: view.getFloat64(offset, littleEndian),
    lat: view.getFloat64(offset + 8, littleEndian),
  };
}
