name: Delete Neon preview branch

# Deletes the pull request's Neon branch (created by the E2E job in ci.yml)
# when the pull request is closed or merged.
on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  delete-branch:
    if: vars.NEON_PROJECT_ID != ''
    runs-on: ubuntu-latest
    steps:
      - uses: neondatabase/delete-branch-action@v3.2.1
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: preview/pr-${{ github.event.number }}
          api_key: ${{ secrets.NEON_API_KEY }}
